Prettify code

diff --git a/resign-archive b/resign-archive
--- a/resign-archive
+++ b/resign-archive
@@ -4,28 +4,26 @@
 
 ARCHIVE_FOLDER=$1
 echo ARCHIVE_FOLDER $ARCHIVE_FOLDER
+
 PROVISION_PROFILE=$2
 echo PROVISION_PROFILE $PROVISION_PROFILE
+
 SIGNATURE=$3
 echo SIGNATURE $SIGNATURE
+
 CERTIFICATE_NAME=$4
 echo CERTIFICATE_NAME $CERTIFICATE_NAME
 
 function clean_up {
-
 # Perform program exit housekeeping
 # Optionally accepts an exit status
-echo cleanup
-#echo "tempfile $TEMP_FILE"
-#echo "$build_log"
-#    cat "$TEMP_FILE" >> "$build_log"
-#        rm -f "$TEMP_FILE"
-            if (( "${1:-0}" > 0 ));then
-                         echo "failed build on step $1"
-                             else
-                                          echo "build succeeded"
-                                              fi  
-                                                  exit $1
+    echo cleanup
+    if (( "${1:-0}" > 0 ));then
+        echo "failed build on step $1"
+    else
+        echo "build succeeded"
+    fi  
+    exit $1
 }
 
 function error_exit {
@@ -39,34 +37,36 @@ trap clean_up SIGHUP SIGINT SIGTERM
 
 APP_FOLDER=$(find "$ARCHIVE_FOLDER" -iname "*.app")
 if [ $? -ne 0 ];then
+
     error_exit 1 
-    fi
+fi
+
+
 NEW_PROVISION_PROFILE="$APP_FOLDER/embedded.mobileprovision"
 XCENT="$APP_FOLDER/archived-expanded-entitlements.xcent"
 CODE_SIGNATURE_FOLDER="$APP_FOLDER/_CodeSignature"
 RESOURCES_PLIST="$APP_FOLDER/ResourceRules.plist"
 
-
-
-
-
-echo APP_FOLDER $APP_FOLDER
 PROFILE_GREP=$(grep -a -A1 'application-identifier' "$PROVISION_PROFILE")
+echo PROFILE_GREP "$PROFILE_GREP"
 if [ $? -ne 0 ];then
     error_exit 2
-    fi
-echo PROFILE_GREP "$PROFILE_GREP"
+ fi
+
+
 BUNDLE_IDENTIFIER=$(ruby -e "puts /<string>(.*)<\/string>/.match(\"$PROFILE_GREP)\")[1]") 
 if [ $? -ne 0 ];then
+    echo BUNDLE_IDENTIFIER $BUNDLE_IDENTIFIER
     error_exit 3
-    fi
+fi
+
+
 KEYCHAIN_IDENTIFIER="$(echo $BUNDLE_IDENTIFIER | cut -d '.' -f1)"
 if [ $? -ne 0 ];then
+    echo KEYCHAIN_IDENTIFIER $KEYCHAIN_IDENTIFIER
     error_exit 4
-    fi
+fi
 
-echo BUNDLE_IDENTIFIER $BUNDLE_IDENTIFIER
-echo KEYCHAIN_IDENTIFIER $KEYCHAIN_IDENTIFIER
 
 rm -rf "$CODE_SIGNATURE_FOLDER" || error_exit 5
 
